### ISSUE TITLE
Unable to compile when 'offscreenCanvasPonyFill' is imported

### ISSUE THREAD

**Issue by tchannagiri** [GMOD/jbrowse-plugin-template#14]
Hello Devs,

I have been trying to follow the tutorial on creating renderer plugins here: https://jbrowse.org/jb2/docs/developer_guide#creating-custom-renderers

When the clone this repo and attempt to create a renderer that uses 'offscreenCanvasPonyFill' as is used in the tutorial, I get the following error (I believe from tsdx):

> ✖ Failed to compile
> Error: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)
> 
> at /var/www/html/jbrowse-plugin-2/node_modules/canvas/build/Release/canvas.node:1:0

and a slew of import errors such as:

> 'fs' is imported by fs?commonjs-external, but could not be resolved – treating it as an external dependency

It seems that tsdx is attempting to compile the serverside version of the canvas library and the 'canvas.node' binary file. Perhaps something in the compiler configuration must be updated to ignore such files?

Also, when I remove the 'offscreenCanvasPonyFill'  code and just return 'null' in 'imageData' it compiles fine.

Here is the code from my MyRenderer.ts to reproduce the error:

```
import React from "react"
import { string } from "mobx-state-tree/dist/internal"
import {
  createCanvas,
  createImageBitmap,
} from '@jbrowse/core/util/offscreenCanvasPonyfill';
import PluginManager from '@jbrowse/core/PluginManager';
import { MyReactComponent } from "./components/MyReactComponent";
import ServerSideRendererType from "@jbrowse/core/pluggableElementTypes/renderers/ServerSideRendererType";

export { MyReactComponent }

export function MyRendererFactory(pluginManager: PluginManager) {
  return class MyRenderer extends ServerSideRendererType {
    render(props: Record<string, any>): Promise<Record<string, any>> {
      const { width, height, regions, features } = props
      const canvas = createCanvas(width, height)
      const ctx = canvas.getContext('2d')
      ctx.fillStyle = 'red'
      ctx.drawRect(0, 0, 100, 100)
      const imageData = createImageBitmap(canvas)
      return new Promise<Record<string, any>>((resolve, reject) =>
        {
          resolve(
            {
              reactElement: React.createElement(this.ReactComponent, { }),
              imageData: imageData,
              height: 100,
              width: 100,
            }
          );
        }
      );
    }
  }
}
```

**Comment by cmdcolin** [comment]
it is a bit tricky to know exactly what's goin on without seeing the setup.

perhaps, you could checkout this plugin which includes a custom renderer (it also includes a custom display type that extends from the "linearwiggledisplay" so it is conceptually similar to a wiggle, but draws the little dots like a normal manhattan plot)

https://github.com/cmdcolin/jbrowse-plugin-gwas

you could maybe adapt such a thing to your needs

**Comment by tchannagiri** [comment]
Hey cmdcolin,

Thanks for your message. I have looked at the GWAS renderer in some depth and I see that it extends the WiggleBaseRenderer. I'll see if I can adapt this for my needs. I am trying to extend a regular feature renderer like BoxRenderer/SVGFeatureRender to customize the way elements are “bumped” to allow certain overlapping features to have the same y-coordinate. Using a offscreen canvas is probably not  required for this but I was attempting to follow the plugin development tutorials (which are probably a bit outdated now).

After some testing, it seems to be some configuration issue with Rollup. I made a zero configuration with just Rollup (no tsdx) and ran into the same error after quite a bit of testing. Though I am building the plugin for the browser/umd, the 'canvas' module is being required and concatenated for the node-js version, and the compiler fails trying to compile the ‘canvas.node’ binary. A workaround I found was to modify ‘tsdx.config.js’ to make Rollup treat the ‘canvas’ module as an external with some dummy global name (only for umd/iife builds). Since the module will never be used in these builds it won’t be an issue.

If this is not a bug with the plugin-template but a user error on my part I can close this issue. However, I got the error using a more of less fresh clone of this repos with just a bit of code for my renderer (no modification of the compiler config).

**Comment by cmdcolin** [comment]
you may have found a real issue then, we have indeed had a bit of trouble where we try to switch logic based on whether we think we are in the browser, where sometimes we have assumed that means webpack_require exists. since this is indeed a rollup based config, this would have issues being used. that said, if you are using Svg based renderers, you shouldn't have to use the offscreenCanvasPonyfill

Here is maybe a starter guide for creating a svg type renderer https://jbrowse.org/jb2/docs/developer_guide#rendering-svg

**Comment by cmdcolin** [comment]
note that the "rendering" and the "renderer" are the same thing in this case so SvgFeatureRendererReactComponent==SvgFeatureRendering

with offscreen canvas based renderers, the "rendering" component is a react component that puts a canvas with the results of the offscreen canvas polyfill.

for a "svg" or react component based renderer, the "rendering" is just the react component, no offscreen canvas polyfill needed

**Comment by tchannagiri** [comment]
Thanks for the explanation of how SVGFeaturerRenderer works. You're right that I probably won't need the offscreen canvas for my purposes, so I'll go about figuring out how to hack the react components of SVGFeaturerRenderer.

Since this seems to be a compiler configuration issue with little bearing on the application logic I'll go ahead and close this for now. I'm fairly new to web-dev but it seems that Javascript nowday's has it own verision of 'make-file hell' from good old C++, with all its transpilation, bundling, and whatnot.

**Comment by cmdcolin** [comment]
I made a new issue number just to make a clean slate to track this because I do believe it is a valid issue https://github.com/GMOD/jbrowse-plugin-template/issues/15

also really interesting to see how far you are diving into the code! it is certainly a fairly complex system so do let us know if you run into anything else if you have ideas to make things easier

**Comment by tchannagiri** [comment]
If I’m able to discover anything useful I’ll definitely let you know. It's an exciting project and honestly I’ve learned quite a bit by diving into the code. 

If I have time would be to figure out how to get Webpack to work with this plugin template and make a PR. It would be good to have the consistency with the make jbrowse-components repo.
