### ISSUE TITLE
Purpose of postinstall step?

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-plugin-template#17]
What is the purpose of the postinstall step in the plugin? I think it can make installation of plugins for developers working on them more confusing if it fails, so it could be useful to remove

**Comment by garrettjstevens** [comment]
See [here](https://github.com/GMOD/jbrowse-components/pull/1578#issue-772455635), there's a bug in TSDX that needs to get fixed with patch-package in the postinstall. #16 would get rid of the postinstall.

**Comment by cmdcolin** [comment]
Would be interested in seeing 16 land then :)

**Comment by cmdcolin** [comment]
we no longer have a postinstall but we do have the prepare script. suggested for removal in #31 but this issue can close
