### ISSUE TITLE
Plugin build errors on unused variables e.g. too strict

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-plugin-template#3]
The current plugin build settings fail during `yarn start` if there is an unused variable for example

This I think it too strict of a setting during development since you can end up with an unused variable all the time while coding

Possibly suggest removing these from tsconfig

```
    // noUnused* overlap with @typescript-eslint/no-unused-vars, can disable if duplicative
    "noUnusedLocals": true,
    "noUnusedParameters": true,

```

**Comment by cmdcolin** [comment]
Note that technically this is in jbrowse-components too

**Comment by garrettjstevens** [comment]
What if we have a development-specific tsconfig? The development one could extend the normal one and make some of the options a bit more lenient. Then the `yarn start` command could pass `--tsconfig tsconfig.dev.json` to `tsdx watch`.

**Comment by cmdcolin** [comment]
The unused variable rule I think is not necessary for people developing plugins. If needed we can enable it for our core codebase but I think it's not useful for developers of plugins
