### ISSUE TITLE
Don't build minified version during development

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-plugin-template#37]
I found that disabling the minified build during devtime reduces my computer going 100% significantly

We could even consider using something like esbuild at devtime which is the vite way.

Here is the way I hacked it to work in my rollup config, but this just disables minifying entirely

```

const r = createRollupConfig(globals.default, {
  includeUMD,
  includeCJS,
  includeESMBundle,
  includeNPM,
})[0]

const config = {
  ...r,
  output: r.output[0]
}

export default config
```

**Comment by garrettjstevens** [comment]
You can also disable minified builds with `NODE_ENV`, e.g.
```
NODE_ENV=development yarn rollup --config --watch
```
Could be worth adding to the default command in package.json.

**Comment by cmdcolin** [comment]
ya, i'd say it would probably be good to add that to the default if that fixes it
